SB-22541 : New timestamp columns are added for course and page
project-sunbird/sunbird-utils pull request #1007
Opened 2021-04-21 12:26 UTC by neha0305verma

2021-04-23 05:33 UTC, PradyumnaNagendra requested changes

2021-04-23 05:33 UTC, PradyumnaNagendra commented on sunbird-cassandra-migration/cassandra-migration/src/main/resources/db/migration/cassandra/V1.120_cassandra.cql
> +ALTER TABLE sunbird_courses.course_batch ADD (created_date timestamp, start_date timestamp, end_date timestamp, enrollment_enddate timestamp, updated_date timestamp);
add If Not Exists

2021-04-23 10:02 UTC, PradyumnaNagendra approved these changes

2021-04-27 07:23 UTC, maheshkumargangula approved these changes

2021-04-27 07:23 UTC, merged