SB-29553 | Enhancements for User and Org Data required for iGOT
project-sunbird/sunbird-utils pull request #1095
Opened 2022-04-12 14:06 UTC by karthik-tarento

Implementation for JIRA Story #SB-29553

2022-04-21 12:26 UTC, reshmi-nair requested changes

2022-04-21 12:26 UTC, reshmi-nair commented on sunbird-es-utils/src/main/resources/mappings/org-mapping.json
> +        },
@karthik-tarento Please remove the ES mapping changes from here and raise a PR against https://github.com/project-sunbird/sunbird-devops/tree/master/ansible/roles/es-mapping/files/

2022-04-26 15:01 UTC, karthik-tarento commented
@reshmi-nair -- PR is updated as per the review comments. Please review this and merge

2022-04-28 06:54 UTC, amit-tarento approved these changes

2022-04-28 10:36 UTC, reshmi-nair approved these changes

2022-04-28 11:06 UTC, maheshkumargangula approved these changes

2022-04-28 11:07 UTC, merged